name: Deploy Cloud Function

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ingest-weather-data-func/**'

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  deploy-gcp-function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: 'actions/checkout@v4'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Zip Function Code
        run: |
          cd ingest-weather-data-func
          zip -r ../function.zip .
        shell: bash

      - name: Upload Function Code to GCS Bucket
        run: |
          gsutil cp function.zip gs://${{ secrets.GCP_PROJECT_ID }}-function-bucket/
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Deploy Google Cloud Function
        run: |
          gcloud functions deploy ingest-weather-data-func \
            --entry-point fetch_weather_data \
            --runtime python310 \  # Adjust runtime based on your code
            --trigger-http \
            --allow-unauthenticated \
            --region us-central1 \
            --source gs://${{ secrets.GCP_PROJECT_ID }}-function-bucket/function.zip \
            --project ${{ secrets.GCP_PROJECT_ID }}

